### ISSUE TITLE
can the model detect other traffic objects? 

### ISSUE THREAD

**Issue by jy1521729** [hustvl/YOLOP#10]
The demo results of object detection only show cars. Can the model detect other traffic objects? such as traffic signs and traffic lights?

**Comment by Riser6** [comment]
> The demo results of object detection only show cars. Can the model detect other traffic objects? such as traffic signs and traffic lights?

Of course！

**Comment by jy1521729** [comment]
Great! If detect other traffic objects, Do I need to train a new model? Can I use the weight 'end-to-end.pth' directly?

**Comment by Riser6** [comment]
> Great! If detect other traffic objects, Do I need to train a new model? Can I use the weight 'end-to-end.pth' directly?
Yes! You need to train a new model.
