### ISSUE TITLE
Can't run demo with custom images

### ISSUE THREAD

**Issue by callmesora** [hustvl/YOLOP#124]
When I try to run the demo with a custom image it gives me this. 
I've tried to convert the image to 1280x720 but the error still occurs

Traceback (most recent call last):
  File "tools/demo.py", line 179, in <module>
    detect(cfg,opt)
  File "tools/demo.py", line 132, in detect
    img_det = show_seg_result(img_det, (da_seg_mask, ll_seg_mask), _, _, is_demo=True)
  File "/xavier_ssd/YOLOP/lib/utils/plot.py", line 57, in show_seg_result
    img[color_mask != 0] = img[color_mask != 0] * 0.5 + color_seg[color_mask != 0] * 0.5
IndexError: boolean index did not match indexed array along dimension 0; dimension is 621 but corresponding boolean dimension is 568

**Comment by Pavithree** [comment]
Hello!

I am facing the same issue, could you please tell me if you found a fix?

Thank you!
