### ISSUE TITLE
Extremely low P value while training on BDD100K

### ISSUE THREAD

**Issue by naruarjun** [hustvl/YOLOP#13]
Hello,
Thank you for the great work on this project. While training on BDD100K, the Precision value for object detection I get is extremely low.
```
Driving area Segment: Acc(0.967)    IOU (0.832)    mIOU(0.897)
Lane line Segment: Acc(0.626)    IOU (0.250)  mIOU(0.617)
Detect: P(0.049)  R(0.885)  mAP@0.5(0.728)  mAP@0.5:0.95(0.391)
```

Am I doing something wrong? The other values match the values given in the readme, but Precision is not given so I don't have a reference.

**Comment by naruarjun** [comment]
I have found the reason, it is because the code reports P and R for the highest recall IOU. I believe it would be more beneficial to report the highest F1 IOU.

**Comment by RahulRewale** [comment]
Hi @naruarjun @Riser6 

Where is this logic?

I am getting below results after training for 200 epochs on BDD100k dataset (13 classes):
```
Driving area Segment: Acc(0.968)    IOU (0.830)    mIOU(0.896)
Lane line Segment: Acc(0.585)    IOU (0.462)  mIOU(0.724)
Detect: P(0.769)  R(0.193)  mAP@0.5(0.177)  mAP@0.5:0.95(0.094)
```

As you can see, I am getting very low recall and mAP values. Do you know what could be wrong?

**Comment by s0966066980** [comment]
> Hi @naruarjun @Riser6
> 
> Where is this logic?
> 
> I am getting below results after training for 200 epochs on BDD100k dataset (13 classes):
> 
> ```
> Driving area Segment: Acc(0.968)    IOU (0.830)    mIOU(0.896)
> Lane line Segment: Acc(0.585)    IOU (0.462)  mIOU(0.724)
> Detect: P(0.769)  R(0.193)  mAP@0.5(0.177)  mAP@0.5:0.95(0.094)
> ```
> 
> As you can see, I am getting very low recall and mAP values. Do you know what could be wrong?


Did you solve it? I am using your 13-class YOLOP.

**Comment by RahulRewale** [comment]
@s0966066980 
As per my experiments, not using the focal loss (setting _C.LOSS.FL_GAMMA to 0 in default.py) improves recall value and decreases precision.

When I set it to 1.5 or 2.0, recall was < 0.2, and when I set it to 0.0, recall was ~ 0.32. This is still not good, but since the authors haven't shared the results, I don't know what should be the target value.
