### ISSUE TITLE
Lane Type Classification

### ISSUE THREAD

**Issue by tfidmmatthew** [hustvl/YOLOP#143]
Does anybody know how to train the model with lane type classification (e.g. Double yellow)?

Thanks all

**Comment by tfidmmatthew** [comment]
In YOLOP.py line 492,

[ 16, Conv, [256, 128, 3, 1]],   #34
[ -1, Upsample, [None, 2, 'nearest']],  #35
[ -1, BottleneckCSP, [128, 64, 1, False]],  #36
[ -1, Conv, [64, 32, 3, 1]],    #37
[ -1, Upsample, [None, 2, 'nearest']],  #38
[ -1, Conv, [32, 16, 3, 1]],    #39
[ -1, BottleneckCSP, [16, 8, 1, False]],    #40
[ -1, Upsample, [None, 2, 'nearest']],  #41
[ -1, Conv, [8, 2, 3, 1]] #42 Lane line segmentation head

Should I copy this segment for other lane type segmentation?

**Comment by abhigoku10** [comment]
@tfidmmatthew  were u able to solve this ? if so can u share the solution 
Thanks in adavance
