### ISSUE TITLE
在训练自己数据集时，发现标注框大小没有变，但是中心点有偏移

### ISSUE THREAD

**Issue by zilong-ding** [hustvl/YOLOP#161]
在run文件夹下的可视化文件夹中看gt图像，发现标注框有偏移，但是在bdd100k上训练时却没有，然后我确认标注数据没有错误，格式转换也是转成了bdd100k中xyxy的形式，然后我看验证时的数据变换也没有发现问题，不知道是为什么会这样？
![0N7_H_YJFN(W{(NYLPOB)AB](https://user-images.githubusercontent.com/71497754/197139773-571fce6c-1296-4ce2-b44a-3beccde1895b.png)

**Comment by zilong-ding** [comment]
已经找到原因了，是default文件中图像大小没有改

**Comment by wwzh2015** [comment]
> 已经找到原因了，是default文件中图像大小没有改

不是会自动缩放padding吗？

**Comment by wwzh2015** [comment]
> > > 已经找到原因了，是default文件中图像大小没有改
> > 
> > 
> > 不是会自动缩放padding吗？
> 
> 自动缩放padding也是根据default中的图像大小来缩放的，我自己的数据大小和原本default中不一致导致标注框偏移

哦，明白了，你说的是训练数据不一致，我以为是推理呢

**Comment by QinghuanWei** [comment]
你是只训练检测的部分吗，如果要训练检测和分割，请问应该怎么设置啊

**Comment by zilong-ding** [comment]
> 你是只训练检测的部分吗，如果要训练检测和分割，请问应该怎么设置啊

我是都训练的，主要是在config/default.py里面设置，我记得是这样，
