### ISSUE TITLE
we need opset = 11 version of the ONNX model

### ISSUE THREAD

**Issue by misaka0316** [hustvl/YOLOP#174]
你好
      我们再将你模型转换到部署使用的引擎时，转换工具要求opset=11 / 10版本，而github上为opset=13版本，在使用给出的ONNX生成工具生成ONNX时，生成的模型与github上完全不一致。请求您给出一个opset = 11的ONNX可用版本，万分感谢。

**Comment by misaka0316** [comment]
此问题以解决，使用pythorch1.7.1  cu11.0  版本即可正确导出模型

**Comment by misaka0316** [comment]
此问题以解决，使用pythorch1.7.1 cu11.0 版本即可正确导出模型

**Comment by happyday-lkj** [comment]
您好，使用export_onnx.py文件导出onnx文件时，报错`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./weights/yolopv2-test-480-640.onnx failed:Node (Mul_1131) Op (Mul) [ShapeInferenceError] Incompatible dimensions`

请问又遇到过吗
