### ISSUE TITLE
Fix the train.py RuntimeError:a view of a leaf Variable that requires grad is being used in an in-place operation when running... issue

### ISSUE THREAD

**Issue by PigLogic-Cyber** [hustvl/YOLOP#18]
If you meet the same issue as I am, you can try as follow to fix it:

![image](https://user-images.githubusercontent.com/85934030/132078651-0787501e-d947-4554-a269-88c477fc53f9.png)

Works for me, good luck :-)

**Comment by naruarjun** [comment]
#17, I believe this is a better fix, and this was the final fix that was merged on YOLOv5

**Comment by PigLogic-Cyber** [comment]
Thx for your advice, and thx for your great job, I'll check out for myself. Sorry for posing a weird issue here, since I do not know much manner here in Github (｡･ω･)~
