### ISSUE TITLE
Fineturning

### ISSUE THREAD

**Issue by zhangbaoj** [hustvl/YOLOP#22]
Hello, if I want to detect people, can I make fineturning on the basis of your weight? For example, after we labeled people's images, we use end-to-end.pth to continue training for models.

**Comment by Riser6** [comment]
Thanks for your interest in our project. In fact, the BDD dataset contain the category of pedestrian, so I recommend you start your training from scratch using our framework.

**Comment by zhangbaoj** [comment]
Thank you very much for your answers. But if the type I want to detect is not in BDD100k, can I use the fineturning method, such as stone.

**Comment by Riser6** [comment]
You can try.

**Comment by zhangbaoj** [comment]
OK. Thank you.
