### ISSUE TITLE
--conf-thres and --iou-thres

### ISSUE THREAD

**Issue by zhangbaoj** [hustvl/YOLOP#24]
Hello, why when I detect images, no matter what I change the values of --conf-thres and --iou-thres to, the detection result remains the same. What's the matter? 
The command is as follows: 
python tools/demo.py --source inference/videos/1.mp4 --iou-thres 0.99 --conf-thres 0.999 --device 0

**Comment by Riser6** [comment]
Thanks for your interest in our project.  In the line 102 of tools/demo.py:
det_pred = non_max_suppression(inf_out, conf_thres=0.25, iou_thres=0.45, classes=None, agnostic=False)
You can try to modify it here!
