### ISSUE TITLE
onnx export problem

### ISSUE THREAD

**Issue by kadirbeytorun** [hustvl/YOLOP#25]
Hello,

Thank you for your great work. I was trying to export your trained model to onnx using torch.onnx.export function. Yet I received the following error.
`RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type builtin_function_or_method`

Is your model compatible to convert to onnx?

And, in your activations.py script I observed that you replaced hardsigmoid with hardtanh. 
```
class Hardswish(nn.Module):  # export-friendly version of nn.Hardswish()
    @staticmethod
    def forward(x):
        # return x * F.hardsigmoid(x)  # for torchscript and CoreML
        return x * F.hardtanh(x + 3, 0., 6.) / 6.  # for torchscript, CoreML and ONNX
```
Yet when I export the model to torch.jit using trace, there seems to be aten::hardswish functions in the model nonetheless. What am I missing?

Thanks in Advance, Kind Regards

**Comment by yyuzhongpv** [comment]
FYI.

https://github.com/hpc203/YOLOP-opencv-dnn

**Comment by kadirbeytorun** [comment]
@yyuzhongpv Oh thanks mate, that repository seems to have shared onnx model also.
I will check it out for sure

**Comment by DefTruth** [comment]
> Yet when I export the model to torch.jit using trace, there seems to be aten::hardswish functions in the model nonetheless. What am I missing?
> 
> Thanks in Advance, Kind Regards

See this PR:  https://github.com/hustvl/YOLOP/pull/30     
My branch:  https://github.com/DefTruth/YOLOP  

Features:      

*  multi version with different input size:    
    *  yolop-320-320.onnx
    *  yolop-640-640.onnx
    *  yolop-1280-1280.onnx

* details for how to export YOLOP to onnx file:  
    *  common2.py (for onnx export friendly)
    *  export_onnx.py (how to export)
    * command:  
    ```shell 
    PYTHONPATH=. python3 ./export_onnx.py --height 640 --width 640
    PYTHONPATH=. python3 ./export_onnx.py --height 1280 --width 1280
    PYTHONPATH=. python3 ./export_onnx.py --height 320 --width 320
    ```
* details for how to test YOLOP using .onnx files:  
   *  test_onnx.py  
   *  command:
   ```shell
   PYTHONPATH=. python3 ./test_onnx.py --weight yolop-640-640.onnx --img ./inference/images/9aa94005-ff1d4c9a.jpg
   ```

* the output of converted .onnx:    

![image](https://user-images.githubusercontent.com/31974251/133256550-3f55a617-8a43-453f-b156-672ddb3f4f93.png)

**Comment by kadirbeytorun** [comment]
@DefTruth Examined your work now, its impressive.

You changed slice layer with two step slice right? Since onnx doesn't support 2 slice at the same time.

Aside from this particular project, I saw on your repository that you worked with many Onnx friendly projects, which leads me to believe you convert your models from Onnx to a NPU framework. May I ask which embedded SoCs you working at?

**Comment by DefTruth** [comment]
> @DefTruth Examined your work now, its impressive.
> 
> You changed slice layer with two step slice right? Since onnx doesn't support 2 slice at the same time.
> 
> Aside from this particular project, I saw on your repository that you worked with many Onnx friendly projects, which leads me to believe you convert your models from Onnx to a NPU framework. May I ask which embedded SoCs you working at?

1: i am not encounter a slice problem when i export YOLOP to .onnx file, so i don't not change Focus layer.  The version of tools i used are:  
```shell  
import onnx
import onnxruntime
import torch
onnx.__version__
'1.8.0'
onnxruntime.__version__
'1.7.0'
torch.__version__
'1.8.1'
```    
2: for my other onnx friendly projects, the tests were passed at Windows/MacOS/Linux, see issues. yet, i did not try to test it in Arm, etc. you can try it.

**Comment by kadirbeytorun** [comment]
@DefTruth It must be about onxx and pytorch version I guess, double slice was not supported in older versions I think.

Thanks for your help, I am examining your repository, you have done an absolutely amazing job with it. I will check out your other projects afterwards also.
