### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by zhuyiliulian** [hustvl/YOLOP#27]
![image](https://user-images.githubusercontent.com/83818851/132936853-7d6e2171-c999-4b4d-bf4e-ddeec3c9a907.png)
![image](https://user-images.githubusercontent.com/83818851/132936874-b2be460b-25e9-476d-ad69-46342f800946.png)
why can come this trouble

**Comment by xinshoushangludd** [comment]
用代码可以运行，python tools/demo.py --source inference/image
