### ISSUE TITLE
Can you make a tutorial for labelling?

### ISSUE THREAD

**Issue by datvuthanh** [hustvl/YOLOP#3]
Can you make a tutorial for labelling?

Thank you.

**Comment by Riser6** [comment]
I will make it up as soon as possible! Thank you for your suggestion!

**Comment by Riser6** [comment]
> Can you make a tutorial for labelling?
> 
> Thank you.

I will make it up as soon as possible! Thank you for your suggestion!

**Comment by Riser6** [comment]
> Can you make a tutorial for labelling?
> 
> Thank you.

I have uploaded our training label to Google Drive, which can be downloaded through the link in Readme.md. md. Thank you for your attention and suggestions to our project

**Comment by datvuthanh** [comment]
Thank you!
