### ISSUE TITLE
Is there a method or toolkit to reproduce each annotation data?

### ISSUE THREAD

**Issue by Keiku** [hustvl/YOLOP#31]
Is there a way to reproduce each annotation data (`det_annotations`, `da_seg_annotations`, `ll_seg_annotations`)?

**Comment by Riser6** [comment]
Sorry, we only provide the label data at present. We may provide the generation code in the future. Welcome to continue to pay attention to our project!

**Comment by Keiku** [comment]
I was able to make the following inferences without using YOLOP. You don't need to use YOLOP as it is not a good repository.

![image](https://user-images.githubusercontent.com/199433/173273531-25c81db4-f318-4ec2-a40a-04f181f44a92.png)

![image](https://user-images.githubusercontent.com/199433/173273771-b5dad707-b535-4754-a0d1-e057ebb1198a.png)

**Comment by santhanakrishnan26** [comment]
> I was able to make the following inferences without using YOLOP. You don't need to use YOLOP as it is not a good repository.
> 
> ![image](https://user-images.githubusercontent.com/199433/173273531-25c81db4-f318-4ec2-a40a-04f181f44a92.png)
> 
> ![image](https://user-images.githubusercontent.com/199433/173273771-b5dad707-b535-4754-a0d1-e057ebb1198a.png)

What did you used ?

**Comment by Keiku** [comment]
@santhanakrishnan26
I'm sorry to reply late. For the above segmentation, I use MaskFormer. The Object Detection below is the result using YOLOX. BBD100K's COCO format conversion and visualization are included in the [Maskformer-BDD100K](https://github.com/Keiku/MaskFormer-BDD100K) repository. Maskformer is an old method, so I think it's easier to use mmdetection now. Please check it.
