### ISSUE TITLE
🙃🤪🍀~ A C++ implementation of YOLOP based on ONNXRuntime is released.

### ISSUE THREAD

**Issue by DefTruth** [hustvl/YOLOP#33]
🙃🤪🍀~A C++ implementation of YOLOP based on ONNXRuntime is released at  [lite.ai](https://github.com/DefTruth/lite.ai) now.   All test passed.  
   * [yolop.cpp](https://github.com/DefTruth/lite.ai/blob/main/ort/cv/yolop.cpp)  
   * [yolop-cpp-demo](https://github.com/DefTruth/lite.ai/blob/main/examples/lite/cv/test_lite_yolop.cpp)

**Comment by Riser6** [comment]
Thanks for your wonderful works! Respect!!!
