### ISSUE TITLE
Do you distinguish between direct and alternative for drivable area segmentation task?

### ISSUE THREAD

**Issue by Keiku** [hustvl/YOLOP#35]
Looking at the visualization of the results, `direct` and `alternative` are not separated. Do you separate `direct` and `alternative` for drivable area segmentation task?

**Comment by Riser6** [comment]
Hi, thank you for your attention to our project. Our model does not distinguish direct and alternative driving area. But you can modify our model to separate these two class in drivable area segmentation task.

**Comment by Keiku** [comment]
Thank you for your reply. I understand that.
