### ISSUE TITLE
Error about deployment on Jetson agx xavier

### ISSUE THREAD

**Issue by rsj007** [hustvl/YOLOP#36]
Hi,
I want to employ the project on Jetson agx xavier. When I cmake the toolkits/deply, it appears " Unknown Cmake command 'coda_add_library'". Can you tell me how to solve it or give me some guide for compile?  Thanks a lot!

**Comment by yueyihua** [comment]
coda_add_library --> cuda_add_library

**Comment by callmesora** [comment]
I changed that and I still can't make the cmake. 
I also commented all the lines related to Zed since I don't want to use it. I just want to try inference with my usb cam

**Comment by makcelk123** [comment]
> 



> 我改变了它，但我仍然无法制作cmake。我还评论了与 Zed 相关的所有行，因为我不想使用它。我只想尝试使用我的 USB 摄像头进行推理

您好，请问你的问题得到解决了吗，我也是想在jetson nano上面部署tensorrt，但是我没有zed摄像机，我想用我自己的摄像头进行实时检测。

**Comment by makcelk123** [comment]
> 我改变了它，但我仍然无法制作cmake。我还评论了与 Zed 相关的所有行，因为我不想使用它。我只想尝试使用我的 USB 摄像头进行推理

Hello, have you resolved your issue? I also want to deploy Tensorrt on Jetson Nano, but I don't have a Zed camera. I would like to use my own camera for real-time detection.
