### ISSUE TITLE
ImportError while running `demo.py` because of commented code in `lib.core.postprocess`

### ISSUE THREAD

**Issue by pra-dan** [hustvl/YOLOP#4]
I was about to submit a PR but thought you guys should do it rather.

**Comment by olivia23333** [comment]
Thank you! Fix this bug in the latest commit.

**Comment by pra-dan** [comment]
Its not done yet, should I make a PR? Is that what you mean ?

**Comment by olivia23333** [comment]
Sorry about that, may be you can show more details about the ImportError?

**Comment by pra-dan** [comment]
The issue was
```console
  File "tools/demo.py", line 29, in <module>
    from lib.core.postprocess import morphological_process, connect_components_analysis, fitlane
ImportError: cannot import name 'fitlane' from 'lib.core.postprocess' (/home/YOLOP/lib/core/postprocess.py)
```

But this can be resolved if the code in `'lib.core.postprocess` is uncommented.

**Comment by olivia23333** [comment]
Fix this in the 'import bug fixed' commit. Thank you!
