### ISSUE TITLE
ValueError: cannot reshape array of size

### ISSUE THREAD

**Issue by DaniloXiao** [hustvl/YOLOP#59]
confusionMatrix = count.reshape(self.numClass, self.numClass) ,ValueError: cannot reshape array of size 5 into shape (2,2) , this mistake often occurs.

**Comment by SikandAlex** [comment]
The error is exactly as described. You cannot reshape an array of size 5 into shape (2, 2). The new shape has to respect the size of the original array.

**Comment by DaniloXiao** [comment]
> The error is exactly as described. You cannot reshape an array of size 5 into shape (2, 2). The new shape has to respect the size of the original array.
Sometimes: cannot reshape array of size 9 into shape (2,2),do you have this situation? How to solve it.
