### ISSUE TITLE
dataset not accessible to opencv methods while training

### ISSUE THREAD

**Issue by pra-dan** [hustvl/YOLOP#6]
After downloading the images and annotations/lables, I made the corresponding changes in the `default.py` config and ran `python tools/train.py`. The data seemed to load successfully but then some of the thread workers spit out some errors.
```console
$ python3 tools/train.py
=> creating runs/BddDataset/_2021-08-30-23-52
Namespace(conf_thres=0.001, dataDir='', iou_thres=0.6, local_rank=-1, logDir='runs/', modelDir='', prevModelDir='', sync_bn=False)
AUTO_RESUME: False
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
...
...

load model to device
begin to load data
building database...
100%|████████████████████████████████████████████████████████| 70000/70000 [00:13<00:00, 5352.88it/s]
database build finish
building database...
100%|████████████████████████████████████████████████████████| 10000/10000 [00:01<00:00, 5334.48it/s]
database build finish
load data finished
anchors loaded successfully
tensor([[[0.3750, 1.1250],
         [0.6250, 1.3750],
         [0.5000, 2.5000]],

        [[0.4375, 1.1250],
         [0.3750, 2.4375],
         [0.7500, 1.9375]],

        [[0.5938, 1.5625],
         [1.1875, 2.5312],
         [2.1250, 4.9062]]])
=> start training...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hotify/YOLOP/lib/dataset/AutoDriveDataset.py", line 100, in __getitem__
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'



^CTraceback (most recent call last):
  File "tools/train.py", line 395, in <module>
    main()
  File "tools/train.py", line 323, in main
    epoch, num_batch, num_warmup, writer_dict, logger, device, rank)
  File "/home/hotify/YOLOP/lib/core/function.py", line 51, in train
    for i, (input, target, paths, shapes) in enumerate(train_loader):
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/prefetch_generator/__init__.py", line 92, in __next__
    return self.next()
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/prefetch_generator/__init__.py", line 85, in next
    next_item = self.queue.get()
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/queue.py", line 170, in get
    self.not_empty.wait()
  File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
^C
```

This resulted from OpenCV trying to read an empty file. To further confirm this, I edited `AutoDriveDataset.py` and tried to print the image shape just before `cvtColor()`
```python3
    def __getitem__(self, idx):
        """
        Get input and groud-truth from database & add data augmentation on input

        Inputs:
        -idx: the index of image in self.db(database)(list)
        self.db(list) [a,b,c,...]
        a: (dictionary){'image':, 'information':}

        Returns:
        -image: transformed image, first passed the data augmentation in __getitem__ function(type:numpy), then apply self.transform
        -target: ground truth(det_gt,seg_gt)

        function maybe useful
        cv2.imread
        cv2.cvtColor(data, cv2.COLOR_BGR2RGB)
        cv2.warpAffine
        """
        data = self.db[idx]
        img = cv2.imread(data["image"], cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
        print(f'log: {img.shape}') # My edit
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
...
```
This verifies the claim. Can this be originating from pytorch ? 

Kindly help me in this. Thanks

**Comment by Riser6** [comment]
> After downloading the images and annotations/lables, I made the corresponding changes in the `default.py` config and ran `python tools/train.py`. The data seemed to load successfully but then some of the thread workers spit out some errors.
> 
> ```
> $ python3 tools/train.py
> => creating runs/BddDataset/_2021-08-30-23-52
> Namespace(conf_thres=0.001, dataDir='', iou_thres=0.6, local_rank=-1, logDir='runs/', modelDir='', prevModelDir='', sync_bn=False)
> AUTO_RESUME: False
> CUDNN:
>   BENCHMARK: True
>   DETERMINISTIC: False
> ...
> ...
> 
> load model to device
> begin to load data
> building database...
> 100%|████████████████████████████████████████████████████████| 70000/70000 [00:13<00:00, 5352.88it/s]
> database build finish
> building database...
> 100%|████████████████████████████████████████████████████████| 10000/10000 [00:01<00:00, 5334.48it/s]
> database build finish
> load data finished
> anchors loaded successfully
> tensor([[[0.3750, 1.1250],
>          [0.6250, 1.3750],
>          [0.5000, 2.5000]],
> 
>         [[0.4375, 1.1250],
>          [0.3750, 2.4375],
>          [0.7500, 1.9375]],
> 
>         [[0.5938, 1.5625],
>          [1.1875, 2.5312],
>          [2.1250, 4.9062]]])
> => start training...
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/prefetch_generator/__init__.py", line 80, in run
>     for item in self.generator:
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
>     data = self._next_data()
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
>     return self._process_data(data)
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
>     data.reraise()
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
>     raise self.exc_type(msg)
> cv2.error: Caught error in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/hotify/YOLOP/lib/dataset/AutoDriveDataset.py", line 100, in __getitem__
>     img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
> cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
> 
> 
> 
> ^CTraceback (most recent call last):
>   File "tools/train.py", line 395, in <module>
>     main()
>   File "tools/train.py", line 323, in main
>     epoch, num_batch, num_warmup, writer_dict, logger, device, rank)
>   File "/home/hotify/YOLOP/lib/core/function.py", line 51, in train
>     for i, (input, target, paths, shapes) in enumerate(train_loader):
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/prefetch_generator/__init__.py", line 92, in __next__
>     return self.next()
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/site-packages/prefetch_generator/__init__.py", line 85, in next
>     next_item = self.queue.get()
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/queue.py", line 170, in get
>     self.not_empty.wait()
>   File "/home/hotify/anaconda3/envs/yolop/lib/python3.7/threading.py", line 296, in wait
>     waiter.acquire()
> KeyboardInterrupt
> ^C
> ```
> 
> This resulted from OpenCV trying to read an empty file. To further confirm this, I edited `AutoDriveDataset.py` and tried to print the image shape just before `cvtColor()`
> 
> ```python
>     def __getitem__(self, idx):
>         """
>         Get input and groud-truth from database & add data augmentation on input
> 
>         Inputs:
>         -idx: the index of image in self.db(database)(list)
>         self.db(list) [a,b,c,...]
>         a: (dictionary){'image':, 'information':}
> 
>         Returns:
>         -image: transformed image, first passed the data augmentation in __getitem__ function(type:numpy), then apply self.transform
>         -target: ground truth(det_gt,seg_gt)
> 
>         function maybe useful
>         cv2.imread
>         cv2.cvtColor(data, cv2.COLOR_BGR2RGB)
>         cv2.warpAffine
>         """
>         data = self.db[idx]
>         img = cv2.imread(data["image"], cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
>         print(f'log: {img.shape}') # My edit
>         img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
> ...
> ```
> 
> This verifies the claim. Can this be originating from pytorch ?
> 
> Kindly help me in this. Thanks

What's the version of PyTorch? In our experiment, the version is 1.7.1, and there's no problem. Maybe you could try upgrading Pytorch to this version.

**Comment by GANGKN1** [comment]
Hi, I have the same error here and I got pytorch version 1.7.1, could you give me some suggestions plz, thanks

python                    3.7.11         h6244533_0
python-dateutil      2.8.2           pypi_0    pypi
pytorch                   1.7.1           py3.7_cuda102_cudnn7_0    pytorch

**Comment by danielzhangau** [comment]
I am having the same issue, can anyone help us?

**Comment by danielzhangau** [comment]
> Hi, I have the same error here and I got pytorch version 1.7.1, could you give me some suggestions plz, thanks
> 
> python 3.7.11 h6244533_0 python-dateutil 2.8.2 pypi_0 pypi pytorch 1.7.1 py3.7_cuda102_cudnn7_0 pytorch

Hi pra-dan and GANGKN1,
I was facing the same issue, but now I sort it out by **double checking my dataset structure to see if there are any missing files**, mine has some missing images in the images validation directory which is weird. Anyway, I just re-download it from the link in [README](https://bdd-data.berkeley.edu/)
And note mine PyTorch and torchvision version is same as the one given in README: conda install pytorch==1.7.0 torchvision==0.8.0 cudatoolkit=10.2 -c pytorch.
I now start training with no error.
Happy coding!
