### ISSUE TITLE
References Error

### ISSUE THREAD

**Issue by entropyfeng** [hustvl/YOLOP#7]
Your paper published in arxiv https://arxiv.org/abs/2108.11250 v4,[7] may **MultiNet: Real-time Joint Semantic Reasoning for Autonomous Driving** rather than **R. Chandra and P. Bahl, “Multinet: Connecting to multiple ieee 802.11networks  using  a  single  wireless  card,”  inieeeinfocom2004,  vol.  2.IEEE, 2004, pp. 882–893.**
Thank you!

**Comment by Riser6** [comment]
I' m sorry for this mistakes, I will correct it immediately. Thank you again for your valuable comments!

**Comment by Riser6** [comment]
> Your paper published in arxiv https://arxiv.org/abs/2108.11250 v4,[7] may **MultiNet: Real-time Joint Semantic Reasoning for Autonomous Driving** rather than **R. Chandra and P. Bahl, “Multinet: Connecting to multiple ieee 802.11networks using a single wireless card,” inieeeinfocom2004, vol. 2.IEEE, 2004, pp. 882–893.**
> Thank you!

I' m sorry for this mistakes, I will correct it immediately. Thank you again for your valuable comments!

**Comment by entropyfeng** [comment]
All my best wishes for the future!
