### ISSUE TITLE
how to custom the category for detection ?

### ISSUE THREAD

**Issue by luckyjohnfeng** [hustvl/YOLOP#72]
Hello:

May I know how to custom the category for detection ?

As far as I know, BDD use those categories:

0: pedestrian
1: rider
2: car
3: truck
4: bus
5: train
6: motorcycle
7: bicycle
8: traffic light
9: traffic sign

May I know how to set or change detection category in your code ?

Thank you very much for the help !

John Feng in Shanghai, China

**Comment by real010** [comment]
您好，麻烦问一下您现在知道怎么根据原来yolo那种txt格式组织yolop目标检测的数据吗，怎样生成bdd格式的数据，期待您的回复！

**Comment by qiuqc1** [comment]
您好，请问您现在解决了吗，他这个类别是怎么分的呢
