### ISSUE TITLE
Annotation tool for custom dataset

### ISSUE THREAD

**Issue by luckyjohnfeng** [hustvl/YOLOP#73]
Hello:

I am wondering is there any annotation tool for a custom dataset ?

So that I could make my own dataset ready:

dataset root
│ ├─images
│ │ ├─train
│ │ ├─val
│ ├─det_annotations
│ │ ├─train
│ │ ├─val
│ ├─da_seg_annotations
│ │ ├─train
│ │ ├─val
│ ├─ll_seg_annotations
│ │ ├─train
│ │ ├─val

Then i could start to train on my own dataset.

Thank you very much for your help.

John Feng in Shanghai, China

**Comment by ideafold** [comment]
have a look at scalabel.ai

**Comment by luckyjohnfeng** [comment]
Thank you very much for the reply !
