### ISSUE TITLE
how to generate the lane segmentation mask picture ?

### ISSUE THREAD

**Issue by luckyjohnfeng** [hustvl/YOLOP#74]
May I know how do you generate the lane segmentation mask png picture ?

I do not find the corresponding code in YOLOP yet.

Then how do you make the ll_seg_annotations png pictures?

Thank you very much !

John Feng in Shanghai, China

**Comment by luckyjohnfeng** [comment]
I edit gen_bdd_seglabel.py

Then I could generate this lane mask image:
![0a0a0b1a-7c39d841](https://user-images.githubusercontent.com/72537572/143408715-8ae0221b-039b-4712-b123-14490548097e.png)

I do not know how to generate the training dataset lane mask image:

![0a0a0b1a-7c39d841](https://user-images.githubusercontent.com/72537572/143408910-4c7ee6b6-b9a9-4cab-8e17-fb7702236be6.png)

I appreciate any reference !

**Comment by luckyjohnfeng** [comment]
I figure it out. My code is right, the BDD jason file marks two lines for some lane.

**Comment by p-mishra1** [comment]
@luckyjohnfeng were you able to generate the 2nd image you have posted, if yes how you combined two individual lanes markings ?
