### ISSUE TITLE
About dataset preparation

### ISSUE THREAD

**Issue by luckyjohnfeng** [hustvl/YOLOP#76]
I use CVAT to annotation my dataset.

I do not know how to convert my CVAT annotations to the required data format of YOLOP.

If there is any reference, I will appreciate it.

John Feng from Shanghai

**Comment by ghmchen** [comment]
Hi John, May you share the procedure of converting CVAT annotations to the required data format of YOLOP? Thanks.

**Comment by luckyjohnfeng** [comment]
Yes, here is the reference for you:

https://towardsdatascience.com/extract-annotations-from-cvat-xml-file-into-mask-files-in-python-bb69749c4dc9

You could download CVAT Image 1.0 XML format, then draw mask image, and draw the lane line by OpenCV as the article above.

Best Regards

John

**Comment by ghmchen** [comment]
Hi John,

Thank you for the information. It is really helpful!
Happy Spring Festival!

Cheng
