### ISSUE TITLE
YOLOP 迁移学习？Transfer Learning for YOLOP

### ISSUE THREAD

**Issue by luckyjohnfeng** [hustvl/YOLOP#79]
我想问一下， 如何使用yolop已经训练好的权重，来进行迁移学习 来检测不同的分类？

How to do transfer learning with YOLOP model for custom category object detection ?

John Feng from Shanghai

**Comment by hetao828** [comment]
我也想知道回答，今天训练的时候精确率一直很低，召回率很快提升上去。

**Comment by xinshoushangludd** [comment]
应该是在训练前   在default.py中添加已经训练好了的权重
