### ISSUE TITLE
只想保留三个任务中的可行驶区域，可以给点建议吗？

### ISSUE THREAD

**Issue by jjjjjkkkk** [hustvl/YOLOP#84]

**Comment by Stephenfang51** [comment]
那你输出的时候其他信息不要就可以了？

**Comment by jjjjjkkkk** [comment]
我想用自己的数据集去训练模型，如果不改变代码的话，还需要标注其他的任务，就增加了工作量。车道线的代码可以去掉，但是去掉目标检测时，代码老报错。关键还不知道哪里出了问题。

**Comment by Stephenfang51** [comment]
> 我想用自己的数据集去训练模型，如果不改变代码的话，还需要标注其他的任务，就增加了工作量。车道线的代码可以去掉，但是去掉目标检测时，代码老报错。关键还不知道哪里出了问题。

保留原模型结构， 把监督检测的那个部分的loss拿掉就可以了

**Comment by jjjjjkkkk** [comment]
好，我试试。

**Comment by fengbiao1212** [comment]
> 好，我试试。

您好，可以分享一下只保留可行驶区域的代码吗？
