### ISSUE TITLE
Can't pickle generator objects

### ISSUE THREAD

**Issue by Taeng-ioio** [hustvl/YOLOP#9]
Hello, I'm trying to learn YOLOP model.
python tools/train.py
When the code was executed, a can't pick generator objects error and a Ran out of input error occurred.
Please give me some advice.

**Comment by Riser6** [comment]
Sorry for this bug. This is probably a problem of Pytorch version. In our experiment, the version is 1.7.1, and there's no problem.  if not, maybe you could describe this bug in more detail.

**Comment by Riser6** [comment]
> Hello, I'm trying to learn YOLOP model.
> python tools/train.py
> When the code was executed, a can't pick generator objects error and a Ran out of input error occurred.
> Please give me some advice.

Sorry for this bug. This is probably a problem of Pytorch version. In our experiment, the version is 1.7.1, and there's no problem. if not, maybe you could describe this bug in more detail.

**Comment by Taeng-ioio** [comment]
> > Hello, I'm trying to learn YOLOP model.
> > python tools/train.py
> > When the code was executed, a can't pick generator objects error and a Ran out of input error occurred.
> > Please give me some advice.
> 
> Sorry for this bug. This is probably a problem of Pytorch version. In our experiment, the version is 1.7.1, and there's no problem. if not, maybe you could describe this bug in more detail.

I installed pytorch version 1.7.0 as mentioned in github README.md
I solved this problem but not proper way.

set _C.WORKERS = 0 and solved pick generator bug
after this, cuda out of memory error occured and I've set _C.TRAIN.BATHC_SIZE_PER_GPU = 3 and solved
I'm training now and waiting for the result.
My GPU is GTX 1650 super

thanks

**Comment by Riser6** [comment]
> > > Hello, I'm trying to learn YOLOP model.
> > > python tools/train.py
> > > When the code was executed, a can't pick generator objects error and a Ran out of input error occurred.
> > > Please give me some advice.
> > 
> > 
> > Sorry for this bug. This is probably a problem of Pytorch version. In our experiment, the version is 1.7.1, and there's no problem. if not, maybe you could describe this bug in more detail.
> 
> I installed pytorch version 1.7.0 as mentioned in github README.md
> I solved this problem but not proper way.
> 
> set _C.WORKERS = 0 and solved pick generator bug
> after this, cuda out of memory error occured and I've set _C.TRAIN.BATHC_SIZE_PER_GPU = 3 and solved
> I'm training now and waiting for the result.
> My GPU is GTX 1650 super
> 
> thanks

Thanks for your attention to our project!  Best wishes!
